# Exported from Render on 2025-01-01T22:03:51Z
databases:
- name: db-postgresql
  databaseName: app_production_j3p1
  user: app_production_j3p1_user
  plan: free

services:
- type: web
  name: rails-devcontainer
  runtime: docker
  repo: https://github.com/ValterAndrei/rails-devcontainer
  plan: free
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: db-postgresql
      property: connectionString
  - key: JWT_SECRET_KEY
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  domains:
  - www.valterandrei.life
  - valterandrei.life
version: "1"
