default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  database: app_development

test: &test
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  database: app_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: app_production
